OBJECTS = \
	source/QobiScheme.o \
	$(COMMON_OBJECTS)

AD_OBJECTS = \
	source/QobiScheme-AD.o \
	$(COMMON-OBJECTS)

COMMON_OBJECTS = \
	source/16bit.o \
	source/2x2.o \
	source/bframe.o \
	source/bitio.o \
	source/block.o \
	source/bsearch.o \
	source/combine.o \
	source/ctrlbar.o \
	source/decoders.o \
	source/dither.o \
	source/encode_api.o \
	source/encode_jrevdct.o \
	source/floatdct.o \
	source/frame.o \
	source/frametype.o \
	source/fs2.o \
	source/fs2fast.o \
	source/fs4.o \
	source/fsize.o \
	source/gdith.o \
	source/gray.o \
	source/huff.o \
	source/hybrid.o \
	source/hybriderr.o \
	source/iframe.o \
	source/jcapimin.o \
	source/jcapistd.o \
	source/jccoefct.o \
	source/jccolor.o \
	source/jcdctmgr.o \
	source/jchuff.o \
	source/jcinit.o \
	source/jcmainct.o \
	source/jcmarker.o \
	source/jcmaster.o \
	source/jcomapi.o \
	source/jcparam.o \
	source/jcphuff.o \
	source/jcprepct.o \
	source/jcsample.o \
	source/jctrans.o \
	source/jdapimin.o \
	source/jdapistd.o \
	source/jdatadst.o \
	source/jdatasrc.o \
	source/jdcoefct.o \
	source/jdcolor.o \
	source/jddctmgr.o \
	source/jdhuff.o \
	source/jdinput.o \
	source/jdmainct.o \
	source/jdmarker.o \
	source/jdmaster.o \
	source/jdmerge.o \
	source/jdphuff.o \
	source/jdpostct.o \
	source/jdsample.o \
	source/jdtrans.o \
	source/jerror.o \
	source/jfdctflt.o \
	source/jfdctfst.o \
	source/jfdctint.o \
	source/jidctflt.o \
	source/jidctfst.o \
	source/jidctint.o \
	source/jidctred.o \
	source/jmemmgr.o \
	source/jmemnobs.o \
	source/jquant1.o \
	source/jquant2.o \
	source/jutils.o \
	source/libpnmrw.o \
	source/mb_ordered.o \
	source/mfwddct.o \
	source/mheaders.o \
	source/mono.o \
	source/motionvector.o \
	source/mpeg.o \
	source/nobuff.o \
	source/nojpeg.o \
	source/noparallel.o \
	source/opts.o \
	source/ordered.o \
	source/ordered2.o \
	source/os_dep.o \
	source/param.o \
	source/parseblock.o \
	source/pframe.o \
	source/play_api.o \
	source/play_jrevdct.o \
	source/postdct.o \
	source/psearch.o \
	source/rate.o \
	source/readfile.o \
	source/readframe.o \
	source/rgbtoycc.o \
	source/specifics.o \
	source/subsample.o \
	source/util.o \
	source/util32.o \
	source/video.o \
	source/xflush.o \
