;;; LaHaShem HaAretz U'Mloah

(include "depth.sch")
(include "screen.sch")
(include "visual.sch")
(include "xarc.sch")
(include "xchar2b.sch")
(include "xcharstruct.sch")
(include "xclasshint.sch")
(include "xcolor.sch")
(include "xcomposestatus.sch")
(include "xevent.sch")
(include "xfontprop.sch")
(include "xfontstruct.sch")
(include "xgcvalues.sch")
(include "xhostaddress.sch")
(include "xiconsize.sch")
(include "ximage.sch")
(include "xkeyboardcontrol.sch")
(include "xkeyboardstate.sch")
(include "xlibCONSTANTS.sch")
(include "xlibTYPES.sch")
(include "xmodifierkeymap.sch")
(include "xpoint.sch")
(include "xrectangle.sch")
(include "xrmoptiondescrec.sch")
(include "xrmvalue.sch")
(include "xsegment.sch")
(include "xsetwindowattributes.sch")
(include "xsizehints.sch")
(include "xstandardcolormap.sch")
(include "xtextitem.sch")
(include "xtextitem16.sch")
(include "xtimecoord.sch")
(include "xvisualinfo.sch")
(include "xwindowattributes.sch")
(include "xwindowchanges.sch")
(include "xwmhints.sch")
(include "xws10.sch")
(include "xws2.sch")
(include "xws3.sch")
(include "xws4.sch")
(include "xws5.sch")
(include "xws6.sch")
(include "xws7.sch")
(include "xws8.sch")
(include "xws9.sch")
(include "xwsr4.sch")
(define-external (ynextevent dpy event) xwss)
(define-external (ylookupstring event . opt) xwss)
(define-external (null-pointer? x) xwss)

;;; Tam V'Nishlam Shevah L'El Borei Olam
